### ISSUE TITLE
How is the code compiled?

### ISSUE THREAD

**Issue by claude-abounegm** [onokumus/chaldene#2]
I see in `/docs/assets/js` a `vendor.js`  which is a minified version of all files in `/docs/assets/vendor/`, could you please guide me to what tools you used to accomplish this and have a `dist` folder with all the required files?

Thanks!

**Comment by onokumus** [comment]
Content of the `vendor.js` file:

1.     jquery.min.js
2.     bootstrap.min.js
3.     moment.min.js
4.     metisMenu.min.js
5.     metis-canvas.min.js
6.     screenfull.min.js
7.     loaders.css.js
8.     in-view.min.js

You can use [gulp](https://github.com/gulpjs/gulp) and [gulp-concat](https://github.com/gulp-community/gulp-concat) to merge js files.
