### ISSUE TITLE
Responsive design breaks when table is larger then the given size

### ISSUE THREAD

**Issue by DNWEIJ** [onokumus/chaldene#3]
Hi, 

Thanks for creating this template, looks good and i am trying to use it :-)

I have a question on how to handle a bigger table (meaning either more fields or that fields are wider, like url field) so that the total width will be bigger then the defined window. 

Once this happens (table is bigger), the responsive design breaks. 
This can be seen in the menu, not resizing anymore to the width of the browser (using your third defintion template).

I use the file"third/table-datatable.html" as example: 
When you copy the nr of rows three times (so in total four times) you notice that during resizing of the window, the menu bar doesn't resize.
The nr of columns looks like:
                          <tr>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                            <th>Name</th>
                            <th>Position</th>
                            <th>Office</th>
                            <th>Age</th>
                            <th>Start date</th>
                            <th>Salary</th>
                          </tr>
NOTE: this also happens if you have less columns but larger data (width) of the columns.

I currently am trying to fix this by using settings on the jquery DataTable plugin:
  "scrollX": true,   and trying to use the responsive plugin. 

I was wandering if you have a different solution suggestion to be able to use larger (in width) content  like the example i gave. 

Regards, Daniel

**Comment by decreative1989** [comment]
I Have Same Issue. how to resposive table using x-scroll ?[https://prnt.sc/l0tchx](url)
