### ISSUE TITLE
Minimise box-body from child box

### ISSUE THREAD

**Issue by nyarachm** [onokumus/chaldene#4]
Hi,

Is it possible to minimise a box-body that exists from within another box?

<div class="box"> // **box 1 start**
  <header>
    <h2>Box 1 (parent)</h2>
    <div class="box-tools">
      box-tools
    </div>
  </header>
  <div class="box-body">
    
<div class="box"> // **box 2 start**
  <header>
    <h2>Box 2 (child)</h2>
    <div class="box-tools">
      <a class="fa fa-fw fa-plus" href="#" data-box="collapse"></a>
    </div>
  </header>
  <div class="box-body collapse">
    THIS DOES NOT COLLAPSE/EXPAND
  </div>

</div>

  </div> // **box 2 end**
</div> // **box 1 end**

P.S: Great theme friend

Thanks

**Comment by onokumus** [comment]
@nyarachm 
You can use bootstrap's collapse method. I will update Chaldene admin for bootstrap 4, in following days.

Have a good day.

**Comment by nyarachm** [comment]
Great. Thanks
